In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

# Custom neurons

In [23]:
class Neuron(tf.keras.layers.Layer):
  def __init__(self, name):
    super(Neuron, self).__init__(name=name)
    self.num_outputs = 1
    self.deltaU = 0
    self.local_error = 0
    #self.w = tf.random_normal_initializer()
    self.b = 0.1 ### DEFINE
    self.u = 0
    

  def build(self, input_shape):
    self.w = self.add_weight("kernel",shape=[int(input_shape[-1]),self.num_outputs])
    

  def call(self, inputs, temperature):
    net = tf.matmul(inputs, self.w)
    self.u = 1/(1 + tf.exp((net + self.b)/temperature))
    
    return self.u

In [12]:
neuron = Neuron("test_neuron")
neuron

In [16]:
neuron.name

'test_neuron'

In [15]:
tf.ones([1,2])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [13]:
test = neuron(tf.ones([1,2]))
test

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.2417444]], dtype=float32)>

In [14]:
neuron.w

<tf.Variable 'test_neuron/kernel:0' shape=(2, 1) dtype=float32, numpy=
array([[0.8950521],
       [0.1480875]], dtype=float32)>

---

# CUSTOM MODEL

In [34]:
class SelfReflexiveNetwork(tf.keras.Model):
  def __init__(self):
    super(SelfReflexiveNetwork, self).__init__(name='SelfReflexiveNetwork')
    self.hidden_neuron = Neuron("Hidden")
    self.output_neuron = Neuron("Output")
    self.r = 0.005
  def call(self, input):
    # foward pass
    hidden_layer_out = self.hidden_neuron(input,temperature = 1)
    output_layer_out = self.output_neuron(hidden_layer_out,temperature = 1)
    return output_layer_out
  
  def train_step(self, data):
    ### FOWARD PASS

    ### BACK PROPAGATION

    # Compute error

    # Update weights

    # Compute metrics
    pass

In [35]:
# Construct an instance of CustomModel
input = tf.ones([1,1])
model = SelfReflexiveNetwork()

In [36]:
model.call(input)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.52939236]], dtype=float32)>

---